### ISSUE TITLE
Frontend Functionality - User

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#83]
Take the user logged-in user and do the following on these sites:

header.html
- Display the user name
- Enable the user to logout with the logout button

profile.html
- Display the user name
- Display the statistics of the user

matchresult.html
- Display and set the user as a default value for the first player of the first team

**Comment by czarnecki** [comment]
To logout just use a hyper link to `/logout` and for the username you can use `${#authentication.getName()}` but you need to check if `${#authentication}` is null before calling `.getName()` on it. You can also use `${#authentication.getName()}` to get the default value for Team 1 Player 1. No null check needed there because only logged in users can visit that page.
